### DISCUSSION TITLE
[sui scripts] Ubiquitous Presence

### DISCUSSION THREAD

**Discussion by FrankC01** [ChainMovers/suibase#3] [Ideas]
A number of opportunities present themselves that would be in line with the core capabilities the multi-sui environment scripts have codified.

1. **Active environments (asui)** - Currently this script will determine which, if any, redirects to invoking sui as well as setting/pointing to sui configuration files (i.e. client.yaml, sui.keystore, networkyaml, etc.). However; the function of this script is limited to redirecting invocations to the sui binaries to execute client and/or keytool operations as offered by the sui CLI.
   o **Opportunity** - There is a reasonable probability that the user will also have installed the SUI binaries and, in effect, can represent a 'default' installation outside of the `workdirs` instance. _**This may be a useful consideration when performing the initial `./install` of sui-base as a valid redirect in addition to any clone and build steps from sui repo**_

2. **Third Party (e.g. SDK)** - When ?sui (asui, lsui, etc.) execute, they assess alignment to the localnet, devnet, futurenet configurations. However; some developer interactions with the sui blockchain may be through a language SDK (Python, C#, golang,etc). In order for an SDK to leverage `sui-base` there would be much replication of script/code to get to what `sui-base` achieves. Furthermore, the `asui`, `lsui` is to execute and exit and thereby removing key information such as which location and settings in `client.yaml`, and other configuration context could be used by the SDK execution.
   o **Opportunity** - If existing or new scripts in `sui-base` could convey that to the SDK invocation, said SDK could leverage that power in interacting with SUI blockchain, maintaining different sets of configurations as well as leverage in a more controled and repeatable test environment.  _**This may be a useful consideration to, through existing or new scripts, to more easily integrate SDK needs**_

**Comment by mario4tier** [comment]
About 1. Active environments (asui)
----
Good idea. 

**Proposed solution - Workdir for installed sui binaries** 
./install (and may be a few other script) will automatically create a "cargobinsui" workdir when detecting ~/.cargo/bin/sui.  Will be the default active workdir.

Will work like any other workdir, except it will be all symlinks.

This is how it will look like after making "cargobinsui" active:
  
```
  ~/sui-base/workdirs/active                                     <- symlink to ~/sui-base/workdirs/cargobinsui
  ~/sui-base/workdirs/cargobinsui/config                         <- symlink to ~/.sui/sui_config
  ~/sui-base/workdirs/cargobinsui/sui-repo/target/debug/sui      <- simlink to ~/.cargo/bin/sui
  ~/sui-base/workdirs/cargobinsui/sui-repo/target/release/sui    <- ditto
```
  (yep... there is a bit of "misdirection" with sui-repo/target/debug)

When defined (not clear yet) ENV variables will also be exported.

====

Somewhat related, will add "asui list" and "asui set \<name\>" as the best way to select the active workdir.

We do not want to have to create a "customfuture set-active" script for every workdir variation.

**Reply by FrankC01** [reply]
Like where this is going. I'm thinking, to facilitate env consumption, a script that resolves all the exports to what is active and persists that in a well defined location (thinking `~/.local/bin`) that other tools/apps/sdk can check. Maybe an extended `client.yaml`:
```yaml
envs:
  - alias: devnet
    rpc: "https://fullnode.devnet.sui.io:443"
    ws: ~
    active_address: "0xe58c532315dced9d08fcb9c3aab16eac0d7fbc5f" <-- RELEVANT TO ENV
    keystore:
         File: /Users/fastfrank/.sui/sui_config/sui.keystore # <--- THIS IS RELEVANT TO THIS ENV
  - alias: localnet_SOME_NAME
    rpc: "http://0.0.0.0:9000"
    ws: ~
    active_address: "0xf61b9b9fba51a4e5a4dd288a671162fcecccdbe8" <-- RELEVANT TO ENV
    keystore:
         File: /Users/fastfrank/.sui/sui_config/sui.keystore # <--- THIS IS RELEVANT TO THIS ENV
active_env: devnet
```
Than the only thing changing is `active_env`
